/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Version editable de las pizzas.
 */
export interface PizzasEditableRes { 
    /**
     * Texto del comentario.
     */
    comentario?: string;
    /**
     * Fecha de publicación del comentario
     */
    date?: Date;
    /**
     * Identificador del comentario.
     */
    idComentario?: number;
    /**
     * Identificador del usuario que genera el comentario.
     */
    idUsuario?: string;
}