/**
 * Identity authorization service
 * REST API to manage user's registration and authentication, role management and token generation and validation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Parameters required to create role
 */
export interface CreateRoleParam { 
    _default?: boolean;
    /**
     * Description of the role
     */
    description?: string;
    /**
     * Name of the role
     */
    name: string;
}