/**
 * Identity authorization service
 * REST API to manage user's registration and authentication, role management and token generation and validation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Coordinates } from './coordinates';
import { Role } from './role';

/**
 * Parameters required to create or update user
 */
export interface RegisterParam { 
    address?: Array<Address>;
    avatar?: string;
    /**
     * Password confirmation
     */
    confirmPassword: string;
    /**
     * Indicates if has confirmed his account
     */
    confirmed?: boolean;
    coordinates?: Coordinates;
    /**
     * User email address
     */
    email: string;
    /**
     * Indicates if the will be enabled or not
     */
    enabled?: boolean;
    /**
     * User first name
     */
    firstName: string;
    /**
     * User gender
     */
    gender?: string;
    /**
     * User last name
     */
    lastName: string;
    /**
     * User's password (must be at least 6 characters)
     */
    password: string;
    phone?: string;
    role?: Role;
    /**
     * User timezone
     */
    timezone: string;
}