/**
 * Identity authorization service
 * REST API to manage user's registration and authentication, role management and token generation and validation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Parameters required to reset password
 */
export interface ResetPasswordParam { 
    /**
     * Confirmation of the new value of the password
     */
    confirmPassword: string;
    /**
     * New value of the password
     */
    password: string;
    /**
     * The token included in the reset link
     */
    token: string;
}