/**
 * Identity authorization service
 * REST API to manage user's registration and authentication, role management and token generation and validation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinates } from './coordinates';

/**
 * Parameters required to update an user
 */
export interface UpdateUserParam { 
    avatar?: string;
    /**
     * Indicates if has confirmed his account
     */
    confirmed?: boolean;
    coordinates?: Coordinates;
    /**
     * Indicates if the will be enabled or not
     */
    enabled?: boolean;
    /**
     * User first name
     */
    firstName?: string;
    /**
     * User gender
     */
    gender?: string;
    /**
     * User last name
     */
    lastName?: string;
    phone?: string;
    /**
     * User timezone
     */
    timezone?: string;
}