/**
 * Identity authorization service
 * REST API to manage user's registration and authentication, role management and token generation and validation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Coordinates } from './coordinates';
import { Permission } from './permission';
import { Role } from './role';

export interface User { 
    address?: Array<Address>;
    avatar?: string;
    confirmed?: boolean;
    coordinates?: Coordinates;
    createdAt?: Date;
    email?: string;
    enabled?: boolean;
    firstName?: string;
    gender?: string;
    id?: string;
    lastName?: string;
    permissions?: Array<Permission>;
    phone?: string;
    role?: Role;
    timezone?: string;
    updatedAt?: Date;
}